version: "3.0"

services:
  cbioDB:
    image: "mysql:5.7"
    expose:
      - "3306"
    ports:
      - "3306:3306"
    volumes:
      - ./my.cnf:/etc/my.cnf
      - ./data/mysql:/var/lib/mysql
      - ./data/mysql-log:/var/log/mysql
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}

  cbioportal:
    image: "${DATA_PORTAL_IMAGE}"
    expose:
      - "8080"
    volumes:
      - ./ROOT:/usr/local/tomcat/webapps/ROOT:ro
      - ./portal.properties:/cbioportal/portal.properties:ro
      - ./context.xml:/usr/local/tomcat/conf/context.xml:ro
      - ./tomcat-users.xml:/usr/local/tomcat/conf/tomcat-users.xml:ro
      - ./manager-context.xml:/usr/local/tomcat/webapps/host-manager/META-INF/context.xml:ro
      - ./manager-context.xml:/usr/local/tomcat/webapps/manager/META-INF/context.xml:ro
      - ./setenv.sh:/usr/local/tomcat/bin/setenv.sh:ro
    ports:
      - "8080:8080"
    # links:
      # - cbioDB

